[package]
name = "kgd-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
kgd-application = { path = "../kgd-application" }
kgd-domain = { path = "../kgd-domain" }

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
macaddr.workspace = true
notion-client.workspace = true
openssl.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serenity.workspace = true
sqlx.workspace = true
surge-ping.workspace = true
tokio.workspace = true
tracing.workspace = true
wake-on-lan.workspace = true

[target.'cfg(unix)'.dependencies]
heif.path = "../heif"

[package.metadata.cargo-machete]
ignored = ["openssl"]

[dev-dependencies]
tokio = { workspace = true, features = ["net"] }
